version: 2.1

jobs:
  deploy-serverless:
    docker:
      - image: circleci/node:14  # Use Node.js 14 (or your preferred version)
    steps:
      - checkout

      # Navigate to the `server` folder
      - run:
          name: Navigate to server folder
          command: cd server

      # Install Serverless Framework
      - run:
          name: Install Serverless Framework
          command: sudo npm install -g serverless

      # Restore cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            - v1-dependencies-

      # Install project dependencies
      - run:
          name: Install project dependencies
          command: npm install

      # Cache dependencies
      - save_cache:
          paths:
            - server/node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}

      # Set up AWS credentials
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set region ${AWS_REGION}

      # Deploy the Serverless application
      - run:
          name: Deploy to AWS
          command: serverless deploy

  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "ui/package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Navigate to UI folder
          command: cd ui
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - ui/node_modules
          key: v1-dependencies-{{ checksum "ui/package-lock.json" }}
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: ui
          paths:
            - .next
            - public
            - package.json
            - package-lock.json
            - node_modules

  deploy-nextjs:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: ui
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: vercel --prod --token $VERCEL_TOKEN

workflows:
  deploy-workflow:
    jobs:
      - deploy-serverless:
          filters:
            branches:
              only:
                - circleci-project-setup
      - deploy-nextjs:
          filters:
            branches:
              only:
                - circleci-project-setup