service: server

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs20.x
  environment:
    REGION: eu-west-1
    ENVIRONMENT: dev
    AWS_ACCESS_KEY_ID_VALUE: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY_VALUE: ${env:AWS_SECRET_ACCESS_KEY}

package:
  excludeDevDependencies: false
  patterns:
    - "lib/**"
    - "node_modules/**"

functions:
  getUser:
    handler: lib/user/get-user/controller.handler
    events:
      - httpApi:
          method: GET
          path: /user/{email}
  saveUser:
    handler: lib/user/create-user/controller.handler
    events:
      - httpApi:
          method: POST
          path: /user/save
  saveCategory:
    handler: lib/category/create-category/controller.handler
    events:
      - httpApi:
          method: POST
          path: /category/save
  getCategory:
    handler: lib/category/get-category/controller.handler
    events:
      - httpApi:
          method: GET
          path: /category/{email}
  saveBalance:
    handler: lib/balance/create-balance/controller.handler
    events:
      - httpApi:
          method: POST
          path: /balance/save
  getBalance:
    handler: lib/balance/get-balance/controller.handler
    events:
      - httpApi:
          method: GET
          path: /balance/{email}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    CategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    BalanceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Balance
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: category
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1