service: server

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs20.x
  environment:
    REGION: eu-west-1

package:
  excludeDevDependencies: false
  patterns:
    - "lib/**"
    - "node_modules/**"

functions:
  getUser:
    handler: lib/user/get-user/controller.handler
    events:
      - httpApi:
          path: user/{email}
          method: get
  saveUser:
    handler: lib/user/create-user/controller.handler
    events:
      - httpApi:
          path: user/save
          method: post
  saveCategory:
    handler: lib/category/create-category/controller.handler
    events:
      - httpApi:
          path: category/save
          method: post
  getCategory:
    handler: lib/category/get-category/controller.handler
    events:
      - httpApi:
          path: category/{email}
          method: get
  saveBalance:
    handler: lib/balance/create-balance/controller.handler
    events:
      - httpApi:
          path: balance/save
          method: post
  getBalance:
    handler: lib/balance/get-balance/controller.handler
    events:
      - httpApi:
          path: balance/{email}
          method: get

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    CategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    BalanceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Balance
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: category
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
