service: server

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs20.x
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PATCH
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - "*"
  environment:
    REGION: eu-west-1
    ENVIRONMENT: dev
    AWS_ACCESS_KEY_ID_VALUE: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY_VALUE: ${env:AWS_SECRET_ACCESS_KEY}
    TOKEN_SECRET_KEY: ${env:TOKEN_SECRET_KEY}

package:
  excludeDevDependencies: false
  patterns:
    - "lib/**"
    - "node_modules/**"

functions:
  authorizer:
    handler: lib/authorizer/controller.handler
  getUser:
    handler: lib/user/get-user/controller.handler
    events:
      - httpApi:
          method: GET
          path: /user
  saveUser:
    handler: lib/user/create-user/controller.handler
    events:
      - httpApi:
          method: POST
          path: /register
  loginUser:
    handler: lib/user/login/controller.handler
    events:
      - httpApi:
          method: POST
          path: /login
  saveCategory:
    handler: lib/category/create-category/controller.handler
    events:
      - httpApi:
          method: POST
          path: /category
  getCategory:
    handler: lib/category/get-category/controller.handler
    events:
      - httpApi:
          method: GET
          path: /category
  saveBalance:
    handler: lib/balance/create-balance/controller.handler
    events:
      - httpApi:
          method: POST
          path: /balance
  getBalance:
    handler: lib/balance/get-balance/controller.handler
    events:
      - httpApi:
          method: GET
          path: /balance

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    CategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    BalanceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Balance
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1