service: server

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs20.x
  environment:
    REGION: eu-west-1

package:
  excludeDevDependencies: false
  patterns:
    - 'lib/**'
    - 'node_modules/**'

functions:
  getUser:
    handler: lib/user/controller.handler
    events:
      - httpApi:
          path: user/get
          method: get

  saveUser:
    handler: lib/user/post/controller.handler
    events:
      - httpApi:
          path: user/save
          method: post

  saveCategory:
    handler: lib/category/create-category/controller.handler
    events:
      - httpApi:
          path: expense/save
          method: post

  getCategory:
    handler: lib/category/get-category/controller.handler
    events:
      - httpApi:
          path: expense/{email}
          method: get

Resources:
  TableName:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users

      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  TableName:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Categories
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
