service: server

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    lambdaPort: 3003

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs20.x
  environment:
    REGION: eu-west-1

package:
  excludeDevDependencies: false
  patterns:
    - 'lib/**'
    - 'node_modules/**'

functions:
  getUser:
    handler: lib/user/controller.getUser
    events:
      - httpApi:
          path: user/get
          method: get

  saveUser:
    handler: lib/user/post/controller.handler
    events:
      - httpApi:
          path: user/save
          method: post
