service: server

plugins:
  - serverless-offline
  
provider:
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs20.x
  environment:
    REGION: eu-west-1

package:
  excludeDevDependencies: false
  patterns:
    - 'lib/**'
    - 'node_modules/**'

functions:
  getUser:
    handler: lib/user/controller.getUser
    events:
      - httpApi:
          path: /
          method: get
